### ISSUE TITLE
兄弟 太感谢你了.困扰我半个月的bug 你帮了我大忙...想问下你这边这些方法怎么找到的?

### ISSUE THREAD

**Issue by saurylip** [reneweb/AndroidAsyncSocketExamples#1]

**Comment by reneweb** [comment]
I guess this is outdated right now & I can't reeally help anyway as I don't speak the your language ;)

**Comment by saurylip** [comment]
anyway,thank u very much,your example help me,i will follow u.O(∩_∩)O谢谢
